/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 miles_from_spider-man_across_the_spider_verse.glb
Author: CVRxEarth (https://sketchfab.com/CVRxEarth)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/miles-from-spider-man-across-the-spider-verse-6585b5cd701d4b11a66618e20b7c8df7
Title: Miles from Spider-Man: Across The Spider Verse
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function MilesSpideman(props) {
  const { nodes, materials } = useGLTF('/miles_from_spider-man_across_the_spider_verse.glb')
  
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.S_U_I_T} skeleton={nodes.Object_7.skeleton} />
        <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.M_A_S_K} skeleton={nodes.Object_8.skeleton} />
        <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.E_Y_E_S} skeleton={nodes.Object_9.skeleton} />
      </group>
      {/* <group position={[5, 0, 0]} scale={0.01}>
        <primitive object={nodes.GLTF_created_1_rootJoint} />
        <skinnedMesh geometry={nodes.Object_83.geometry} material={materials.S_K_I_N} skeleton={nodes.Object_83.skeleton} />
        <skinnedMesh geometry={nodes.Object_84.geometry} material={materials.H_A_I_R} skeleton={nodes.Object_84.skeleton} />
        <skinnedMesh geometry={nodes.Object_85.geometry} material={materials.N_E_C_K_P_A_R_T} skeleton={nodes.Object_85.skeleton} />
        <skinnedMesh geometry={nodes.Object_91.geometry} material={materials.S_K_I_N} skeleton={nodes.Object_91.skeleton} />
        <skinnedMesh geometry={nodes.Object_93.geometry} material={materials['40_-Mask.material03.Mask.material03_1_0_0']} skeleton={nodes.Object_93.skeleton} />
        <skinnedMesh geometry={nodes.Object_95.geometry} material={materials.S_U_I_T} skeleton={nodes.Object_95.skeleton} />
        <mesh geometry={nodes.Object_87.geometry} material={materials.S_K_I_N} />
        <mesh geometry={nodes.Object_89.geometry} material={materials.S_K_I_N} />
      </group>
      <group position={[15, 0, 0]} scale={0.01}>
        <primitive object={nodes.GLTF_created_2_rootJoint} />
        <skinnedMesh geometry={nodes.Object_243.geometry} material={materials.S_K_I_N} skeleton={nodes.Object_243.skeleton} />
        <skinnedMesh geometry={nodes.Object_244.geometry} material={materials.H_A_I_R} skeleton={nodes.Object_244.skeleton} />
        <skinnedMesh geometry={nodes.Object_245.geometry} material={materials.N_E_C_K_P_A_R_T} skeleton={nodes.Object_245.skeleton} />
        <skinnedMesh geometry={nodes.Object_251.geometry} material={materials.S_K_I_N} skeleton={nodes.Object_251.skeleton} />
        <skinnedMesh geometry={nodes.Object_253.geometry} material={materials['40_-Mask.material03.Mask.material03_1_0_0']} skeleton={nodes.Object_253.skeleton} />
        <skinnedMesh geometry={nodes.Object_255.geometry} material={materials.S_U_I_T} skeleton={nodes.Object_255.skeleton} />
        <mesh geometry={nodes.Object_247.geometry} material={materials.S_K_I_N} />
        <mesh geometry={nodes.Object_249.geometry} material={materials.S_K_I_N} />
      </group>
      <group position={[10, 0, 0]} scale={0.01}>
        <primitive object={nodes.GLTF_created_3_rootJoint} />
        <skinnedMesh geometry={nodes.Object_403.geometry} material={materials.S_U_I_T} skeleton={nodes.Object_403.skeleton} />
        <skinnedMesh geometry={nodes.Object_404.geometry} material={materials.M_A_S_K} skeleton={nodes.Object_404.skeleton} />
        <skinnedMesh geometry={nodes.Object_405.geometry} material={materials.E_Y_E_S} skeleton={nodes.Object_405.skeleton} />
      </group> */}
    </group>
  )
}

useGLTF.preload('/miles_from_spider-man_across_the_spider_verse.glb')
