/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 miguel_ohara_spider-man_across_the_spider-verse.glb
Author: CVRxEarth (https://sketchfab.com/CVRxEarth)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/miguel-ohara-spider-man-across-the-spider-verse-ea60ca0885574fa8a6d85046dd884a60
Title: Miguel O'hara Spider-Man Across The Spider-Verse
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Ohara(props) {
  const { nodes, materials } = useGLTF('/miguel_ohara_spider-man_across_the_spider-verse.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.229}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={0.01}>
            <primitive object={nodes.GLTF_created_0_rootJoint} />
            <skinnedMesh geometry={nodes.Object_7.geometry} material={materials['S_K_I_N.002']} skeleton={nodes.Object_7.skeleton} />
            <skinnedMesh geometry={nodes.Object_9.geometry} material={materials['B_O_D_Y.001']} skeleton={nodes.Object_9.skeleton} />
            <skinnedMesh geometry={nodes.Object_10.geometry} material={materials['H_E_A_D.001']} skeleton={nodes.Object_10.skeleton} />
            <skinnedMesh geometry={nodes.Object_12.geometry} material={materials['B_A_N_D.001']} skeleton={nodes.Object_12.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/miguel_ohara_spider-man_across_the_spider-verse.glb')
