/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 spiderman_swinganimation_verison_2.glb
Author: Jit Debnath (https://sketchfab.com/jitdebnath2442)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spiderman-swinganimation-verison-2-89b43b37b9984fbab8c7ffeff78724d5
Title: Spiderman SwingAnimation Verison 2
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/spiderman_swinganimation_verison_2.glb')
  const { actions } = useAnimations(animations, group)
 
  useEffect(() => {
    actions["Animation"]
    return () => actions["Animation"].play()
  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.046}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="NWH_Suit_66" position={[30.168, -1.407, -8.316]} rotation={[Math.PI / 2, 0, -0.039]} scale={0.009}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="Tom001_65" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['zhizhuxiamcu_battlebody.002']} skeleton={nodes.Object_7.skeleton} />
                </group>
              </group>
              <group name="OG_Suit_134" position={[-55.195, -41.967, -12.322]} rotation={[Math.PI / 2, 0, -0.261]} scale={0.331}>
                <group name="GLTF_created_1">
                  <primitive object={nodes.GLTF_created_1_rootJoint} />
                  <group name="Tobey001_133" />
                  <skinnedMesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials['Spiderman_Torso_D_1.001']} skeleton={nodes.Object_77.skeleton} />
                  <skinnedMesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials['Spiderman_Web_D.001']} skeleton={nodes.Object_78.skeleton} />
                  <skinnedMesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials['Spiderman_Hands_D.001']} skeleton={nodes.Object_79.skeleton} />
                  <skinnedMesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials['Spiderman_Torso_D.001']} skeleton={nodes.Object_80.skeleton} />
                  <skinnedMesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials['Spiderman_Head_D.001']} skeleton={nodes.Object_81.skeleton} />
                  <skinnedMesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials['Spiderman_Web_D_1.001']} skeleton={nodes.Object_82.skeleton} />
                  <skinnedMesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials['Spiderman_Web_D_2.001']} skeleton={nodes.Object_83.skeleton} />
                  <skinnedMesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials['Spiderman_Boots_D.001']} skeleton={nodes.Object_84.skeleton} />
                  <skinnedMesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials['Spiderman_Lens_D.001']} skeleton={nodes.Object_85.skeleton} />
                </group>
              </group>
              <group name="AmazingSuit_201" position={[0.906, -0.637, 33.017]} rotation={[Math.PI / 2, 0, -0.039]} scale={0.961}>
                <group name="GLTF_created_2">
                  <primitive object={nodes.GLTF_created_2_rootJoint} />
                  <group name="SM001_200" />
                  <skinnedMesh name="Object_155" geometry={nodes.Object_155.geometry} material={materials['Model001_Material001.002']} skeleton={nodes.Object_155.skeleton} />
                  <skinnedMesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials['Model001_Material002.002']} skeleton={nodes.Object_156.skeleton} />
                  <skinnedMesh name="Object_157" geometry={nodes.Object_157.geometry} material={materials['Model001_Material003.002']} skeleton={nodes.Object_157.skeleton} />
                  <skinnedMesh name="Object_158" geometry={nodes.Object_158.geometry} material={materials['Model001_Material004.002']} skeleton={nodes.Object_158.skeleton} />
                  <skinnedMesh name="Object_159" geometry={nodes.Object_159.geometry} material={materials['Model001_Material005.002']} skeleton={nodes.Object_159.skeleton} />
                  <skinnedMesh name="Object_160" geometry={nodes.Object_160.geometry} material={materials['Model001_Material006.002']} skeleton={nodes.Object_160.skeleton} />
                  <skinnedMesh name="Object_161" geometry={nodes.Object_161.geometry} material={materials['Model001_Material007.002']} skeleton={nodes.Object_161.skeleton} />
                </group>
              </group>
              <group name="Miles_Suit_268" position={[-75.151, -56.154, 36.897]} rotation={[Math.PI / 2, 0, -0.263]} scale={0.069}>
                <group name="GLTF_created_3">
                  <primitive object={nodes.GLTF_created_3_rootJoint} />
                  <group name="Miles_Morales_267" />
                  <skinnedMesh name="Object_231" geometry={nodes.Object_231.geometry} material={materials.Default} skeleton={nodes.Object_231.skeleton} />
                  <skinnedMesh name="Object_232" geometry={nodes.Object_232.geometry} material={materials['Material.001']} skeleton={nodes.Object_232.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/spiderman_swinganimation_verison_2.glb')
