/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 superior_spiderman.glb
Author: KhangDuyNguyen189 (https://sketchfab.com/KhangNguyen189)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/superior-spiderman-dd8d6b4342c1473bba5cda722484eeb0
Title: Superior Spiderman
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Spider(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/superior_spiderman.glb')
  const { actions } = useAnimations(animations, group)
  console.log(actions);
  useEffect(() => {
    actions["Idle"].play()
    return () => actions["Idle"].play()
  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.656}>
          <group name="120fb6427e2a4b158fcc415703e7672bfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" />
                  <group name="Object_8" />
                  <group name="Body_sub1group2">
                    <group name="Body_sub1polySurface1" />
                    <group name="Body_sub1Group34295" />
                  </group>
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Body_sub1SpidermanBody} skeleton={nodes.Object_7.skeleton} castShadow receiveShadow/>
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Body_sub1SpidermanBody} skeleton={nodes.Object_9.skeleton} castShadow receiveShadow/>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/superior_spiderman.glb')
